### ISSUE TITLE
 help to return values

### ISSUE THREAD

**Issue by petrospap** [wildantea/php-pdo-mysql-helper-class#3]
Hello!
First thanks for this pdo class!!
I am new to PDO, and I try to learn a bit, I got this problem
based on your examples I try to return all usernames, but shows only one value

    $rs=fetch_all('admin');
     foreach ($rs as $key) {
	// echo $key->username.":".$key->password."<br>";
           $usernames = $key->username;
           return $usernames;
     }
    echo  $usernames;
    shows "admin tea dua"

Iam such a noob I can't fixed!! how to return all names?
Can you please help me on this?

**Comment by wildantea** [comment]
Please learn more about creating function in php, so, u gonna figure out
how to use 'return'

**Comment by petrospap** [comment]
Thanks wildantea, I have already start reading :)
