### ISSUE TITLE
How to get last insert id with custom_query

### ISSUE THREAD

**Issue by petrospap** [wildantea/php-pdo-mysql-helper-class#4]
Hello
I have a complex querie to insert and I cannot use "function insert" so I use "function custom_query"
but I can't find/get lastInsertId
is there any tip/hint how to find it
Thank you

**Comment by petrospap** [comment]
forgot to mention, I have modify the insert function as

```
    public function insert($table,$dat) {

        if( $dat !== null )
        $data = array_values( $dat );
        //grab keys
        $cols=array_keys($dat);
        $col=implode(', ', $cols);

        //grab values and change it value
        $mark=array();
        foreach ($data as $key) {
          $keys='?';
          $mark[]=$keys;
        }
        $im=implode(', ', $mark);
        $ins = $this->pdo->prepare("INSERT INTO $table ($col) values ($im)");
        $ins->execute( $data );
	   $lastId = $this->pdo->lastInsertId();
		if ($ins->rowCount() > 0) {
			return $lastId;
		} else {
		    return false;
		}
    }
```

**Comment by wildantea** [comment]
i have updated the code, you can get last id with this function $db->get_last_id() , just place it after insert statement;

**Comment by petrospap** [comment]
Thanks wildantea this was really useful!

One more question ( No need to open another issue )

I modify the insert function not just to find the last Id, but because I want to check if insert successfully executed.

Also in function delete i modify like this
``` 
public function delete( $table, $where,$id ) {
        $data = array( $id );
        $sel = $this->pdo->prepare("Delete from $table where $where=?" );
        $sel->execute( $data );
        $del=$sel->rowCount();
        if ($del>0) {
            return true;
        } else {
            return false;
        }
    }
```
Do you think that these modifications have a sense?

**Comment by wildantea** [comment]
actually, it will just throw an error, though you didn't add that rowcount for checking whether it's inserted or deleted. but maybe i'll check it later, thanks mat

**Comment by petrospap** [comment]
I close it this issue because is solved :)

From my point of view, errors must displayed only if something critical happened or in debug mode (if exist)
I use your pdo-helper to build my page
so i have added not display errors like this
```
            //$this->pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
	          $this->pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_SILENT);
```
and the only reason that I have added rowcount is to rollback more easier, although I still working on this!!
